sslSocket:
  port: 29999
  nettyPort: 9002
  sslFlag: true
  ##密钥
  server_key_store_password: longshine
  server_trust_key_store_password: longshine

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: lancedb
    password: lancedb
    # 下面为连接池的补充设置，应用到上面所有数据源中
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 50
    minIdle: 50
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 100
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

logging:
  level:
    druid:
      sql:
        Statement: debug
        ResultSet: debug
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
           sql:
            BasicBinder: trace
            BasicExtractor: trace

# sftp
sftp:
  ip: todo
  host: 22
  userName: todo
  userPsw: todo
  localFilePath: D:/sftpDir/
  remoteFilePath: /home/